/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.13.2.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as auth from "../auth.js";
import type * as board from "../board.js";
import type * as games from "../games.js";
import type * as http from "../http.js";
import type * as prizes from "../prizes.js";
import type * as tickets from "../tickets.js";
import type * as users from "../users.js";
import type * as winners from "../winners.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  auth: typeof auth;
  board: typeof board;
  games: typeof games;
  http: typeof http;
  prizes: typeof prizes;
  tickets: typeof tickets;
  users: typeof users;
  winners: typeof winners;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
